### ISSUE TITLE
Allow mocking of executables installed in the system

### ISSUE THREAD

**Issue by xasopheno** [Originate/scriptkeeper#114]
In case the script uses commands that are not installed on the system that the tests are run.
``` yaml
dependencies:
#       this can be install here: asdf.com
        - gcsfuse
protocols:
        - protocol: []
```
