### ISSUE TITLE
Rename yaml fields

### ISSUE THREAD

**Issue by soenkehahn** [Originate/scriptkeeper#182]
I'm wondering whether we should rename `protocols` to `tests` and `protocol` to `steps`. This might be easier to understand without learning the term 'Protocol' that only `scriptkeeper` uses.

This would be a breaking change, but I think that's fine at this point.

**Comment by soenkehahn** [comment]
Any opinions? @data-pup @matthandlersux @hallettj @xasopheno @iphipps

**Comment by soenkehahn** [comment]
It would look like this:
``` yaml
tests:
  # builds a docker image when git repo is clean
  - steps:
    - command: /usr/bin/git status --porcelain
      stdout: ""
    - command: /usr/bin/git rev-parse HEAD
      stdout: "mock_commit_hash\n"
    - /usr/bin/docker build --tag image_name:mock_commit_hash .
  # aborts when git repo is not clean
  - steps:
    - command: /usr/bin/git status --porcelain
      stdout: " M some-file"
    exitcode: 1
```
